### PR TITLE
feat: pinning

### PR DESCRIPTION
**Pull request by hacdias**
Ref.: #518 

## Pin a new hash

[https://gyazo.com/cc95c17262a58052d43230cb756f5c09](https://gyazo.com/cc95c17262a58052d43230cb756f5c09)

# Search

[https://gyazo.com/7e1d694d77174bd6c3493812c11318ab](https://gyazo.com/7e1d694d77174bd6c3493812c11318ab)

# Animation while pinning

[https://gyazo.com/72e7b03963fa2eec270b2516f4f84437](https://gyazo.com/72e7b03963fa2eec270b2516f4f84437)

### CODE REVIEW

**Comment by hacdias** [comment]
https://gyazo.com/50a063449199a3992a23bec940273ce4

**Comment by hacdias** [comment]
I think this is working! I'd like you to that a look: @flyingzumwalt @diasdavid

**Comment by hacdias** [comment]
I think it's done @diasdavid! 🎉 🎉 🎉 Let's merge this?

**Comment by diasdavid** [comment]
Sweeeet!! Awesome work @hacdias :)

**Pull request merged**
