### PR TITLE
refactor: menu

### LINKED ISSUE #560: Two buttons for the same thing
Right now we have two different buttons doing the same thing: turning the daemon on and off.

image

Should they be kept? IMO, we should remove the one from the bottom since it's repetitive. Although, it's more clear what it does than the one from the top right.

/cc @diasdavid

### PR DESCRIPTION
**Pull request by hacdias**
What do you think about something like this?

This:
- is more compact
- is more simple
- has easier navigation. 
- simplifies the process of adding new panes.

### Todo

- [x] Review setup screen
- [x] Light Theme
- [x] Review DOCS on Readme
- [x] Settings inside menubar

### Light Theme

image

image

image

image

### Dark Theme

image

image

image

image

This closes #560.

/cc @ipfs-shipyard/ipfs-gui-team

### CODE REVIEW

**Comment by diasdavid** [comment]
Looking good @hacdias . Is this part of the work to make adding panes easier?

**Comment by hacdias** [comment]
Yes, it will be easier to do so if this gets merged. Basically, on the left we have the available panes and it gets displayed on the right. 

Despites that, I think it's also easier for the end-user to navigate through the application instead of having those options in the bottom left as we have right now.

**Comment by hacdias** [comment]
@diasdavid could you take a look at [this idea](https://github.com/ipfs-shipyard/ipfs-station/blob/debd4fc9716a21e853c45ac7c94fe6a2ec24b3c7/src/js/screens/menu.js), please?

- `panesOrder` is the order by which the options are showed on the menu.
- `panes` are the panes configuration.
- The `this` from the class is binded into the `render` function.

**Comment by hacdias** [comment]
I'd also be in favour of having a lighter theme:

image

Or at least an option to toggle between dark and light. What are your thoughts?

**Comment by hacdias** [comment]
Some still unanswered questions:

- Which should be the "default" pane? I mean, the one which opens by default when we start Station? The node information or files?
- Does it make more sense to have the "close station" button in Settings or in Info? In my opinion, it makes more sense in Settings.
- Related to that, we have #560. Should the 'Shutdown' button really close station? If so, we wouldn't need the previous option.

/cc @machawk1 @diasdavid 

The current state:

image

image

image

image

image

image

image

image

**Comment by diasdavid** [comment]
> Which should be the "default" pane? I mean, the one which opens by default when we start Station? The node information or files?

The Informations Pane

> Does it make more sense to have the "close station" button in Settings or in Info? In my opinion, it makes more sense in Settings.

- Quit Station (as in close the app) - In the Settings
- Stop/Start the daemon - In the corner

> Related to that, we have #560. Should the 'Shutdown' button really close station? If so, we wouldn't need the previous option.

Shutdown/stop should just stop the daemon and not quit station.

Also, default to the dark theme but yes you can have the light theme.

image

image

Once this details are done, I suggest to go ahead and merge and focus on the Pinning feature #571 that will be a stellar feature.

**Comment by diasdavid** [comment]
One more thing:

image

**Comment by hacdias** [comment]
@diasdavid 

image

Should we keep both (circled in red)?

**Comment by hacdias** [comment]
image

@diasdavid may I merge it?

**Comment by diasdavid** [comment]
@hacdias go for it :)

**Pull request merged**
